# Project Routes

| Method | URI | Name | Action | Middleware |
| :--- | :--- | :--- | :--- | :--- |
| GET|HEAD | / |  | Closure | web |
| GET|HEAD | api/sanctum/csrf-cookie |  | App\Http\Controllers\Api\Auth\Preparation\CsrfOwnershipPreparationController@show | api, web, App\Http\Middleware\ApplyIdentityRouteContext:shared_transitional,merchant,observe |
| POST | api/stripe/webhook |  | App\Http\Controllers\Api\Payment\StripeWebhookController@handle | api, App\Http\Middleware\ApplyIdentityRouteContext:shared_transitional,merchant,observe |
| GET|HEAD | api/user |  | Closure | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/admin/cms/blog |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/blog |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| GET|HEAD | api/v1/admin/cms/blog/{blogPost} |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| PUT | api/v1/admin/cms/blog/{blogPost} |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| DELETE | api/v1/admin/cms/blog/{blogPost} |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/blog/{blogPost}/publish |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@publish | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/blog/{blogPost}/schedule |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@schedule | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/blog/{blogPost}/unpublish |  | App\Http\Controllers\Api\Cms\Blog\AdminBlogController@unpublish | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| GET|HEAD | api/v1/admin/cms/doc-sections |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentSectionController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.view |
| POST | api/v1/admin/cms/doc-sections |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentSectionController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.create |
| GET|HEAD | api/v1/admin/cms/doc-sections/{id} |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentSectionController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.view |
| DELETE | api/v1/admin/cms/doc-sections/{id} |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentSectionController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.delete |
| GET|HEAD | api/v1/admin/cms/docs |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.view |
| POST | api/v1/admin/cms/docs |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.create |
| POST | api/v1/admin/cms/docs/reorder |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@reorder | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.update |
| GET|HEAD | api/v1/admin/cms/docs/{id} |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.view |
| PUT | api/v1/admin/cms/docs/{id} |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.update |
| DELETE | api/v1/admin/cms/docs/{id} |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.delete |
| POST | api/v1/admin/cms/docs/{id}/publish |  | App\Http\Controllers\Api\Admin\Cms\Documentation\AdminDocumentController@publish | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin, Spatie\Permission\Middleware\PermissionMiddleware:cms.doc.publish |
| GET|HEAD | api/v1/admin/cms/pages |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/pages |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| GET|HEAD | api/v1/admin/cms/pages/{id} |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| PUT | api/v1/admin/cms/pages/{id} |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| DELETE | api/v1/admin/cms/pages/{id} |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| POST | api/v1/admin/cms/pages/{id}/publish |  | App\Http\Controllers\Api\Admin\Cms\MarketingPage\AdminMarketingPageController@publish | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, Spatie\Permission\Middleware\RoleMiddleware:super_admin |
| GET|HEAD | api/v1/admin/leads |  | App\Http\Controllers\Api\Admin\Lead\AdminLeadController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/admin/leads/{lead} |  | App\Http\Controllers\Api\Admin\Lead\AdminLeadController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| DELETE | api/v1/admin/leads/{lead} |  | App\Http\Controllers\Api\Admin\Lead\AdminLeadController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| PATCH | api/v1/admin/leads/{lead}/status |  | App\Http\Controllers\Api\Admin\Lead\AdminLeadController@updateStatus | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/admin/stores/{store}/brands |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.view |
| POST | api/v1/admin/stores/{store}/brands |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.create |
| GET|HEAD | api/v1/admin/stores/{store}/brands/{brand} |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.view |
| PATCH | api/v1/admin/stores/{store}/brands/{brand} |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.update |
| DELETE | api/v1/admin/stores/{store}/brands/{brand} |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.delete |
| PATCH | api/v1/admin/stores/{store}/brands/{brand}/restore |  | App\Http\Controllers\Api\Admin\Brand\AdminBrandController@restore | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:brand.restore |
| GET|HEAD | api/v1/admin/stores/{store}/categories |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.view |
| POST | api/v1/admin/stores/{store}/categories |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.create |
| GET|HEAD | api/v1/admin/stores/{store}/categories/{category} |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.view |
| PATCH | api/v1/admin/stores/{store}/categories/{category} |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.update |
| DELETE | api/v1/admin/stores/{store}/categories/{category} |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.delete |
| PATCH | api/v1/admin/stores/{store}/categories/{category}/restore |  | App\Http\Controllers\Api\Admin\Category\AdminCategoryController@restore | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:category.restore |
| GET|HEAD | api/v1/admin/stores/{store}/dashboard/recent-orders |  | App\Http\Controllers\Api\Admin\Dashboard\AdminDashboardController@recentOrders | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:dashboard.view |
| GET|HEAD | api/v1/admin/stores/{store}/dashboard/stats |  | App\Http\Controllers\Api\Admin\Dashboard\AdminDashboardController@stats | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:dashboard.view |
| GET|HEAD | api/v1/admin/stores/{store}/dashboard/top-products |  | App\Http\Controllers\Api\Admin\Dashboard\AdminDashboardController@topProducts | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:dashboard.view |
| GET|HEAD | api/v1/admin/stores/{store}/orders |  | App\Http\Controllers\Api\Admin\Order\AdminOrderController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:order.view |
| GET|HEAD | api/v1/admin/stores/{store}/orders/{order} |  | App\Http\Controllers\Api\Admin\Order\AdminOrderController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:order.view |
| PATCH | api/v1/admin/stores/{store}/orders/{order}/cancel |  | App\Http\Controllers\Api\Admin\Order\AdminOrderController@cancel | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:order.cancel |
| PATCH | api/v1/admin/stores/{store}/orders/{order}/refund |  | App\Http\Controllers\Api\Admin\Order\AdminOrderController@refund | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:order.refund |
| PATCH | api/v1/admin/stores/{store}/orders/{order}/status |  | App\Http\Controllers\Api\Admin\Order\AdminOrderController@updateStatus | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:order.update_status |
| GET|HEAD | api/v1/admin/stores/{store}/products |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.view |
| POST | api/v1/admin/stores/{store}/products |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.create |
| GET|HEAD | api/v1/admin/stores/{store}/products/{product} |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.view |
| PATCH | api/v1/admin/stores/{store}/products/{product} |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.update |
| DELETE | api/v1/admin/stores/{store}/products/{product} |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.delete |
| PATCH | api/v1/admin/stores/{store}/products/{product}/restore |  | App\Http\Controllers\Api\Admin\Product\AdminProductController@restore | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:product.restore |
| GET|HEAD | api/v1/admin/stores/{store}/tags | tags.index | App\Http\Controllers\Api\Admin\Tag\AdminTagController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:tag.view |
| POST | api/v1/admin/stores/{store}/tags | tags.store | App\Http\Controllers\Api\Admin\Tag\AdminTagController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:tag.create |
| GET|HEAD | api/v1/admin/stores/{store}/tags/{tag} | tags.show | App\Http\Controllers\Api\Admin\Tag\AdminTagController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:tag.view |
| PUT|PATCH | api/v1/admin/stores/{store}/tags/{tag} | tags.update | App\Http\Controllers\Api\Admin\Tag\AdminTagController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:tag.update |
| DELETE | api/v1/admin/stores/{store}/tags/{tag} | tags.destroy | App\Http\Controllers\Api\Admin\Tag\AdminTagController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:tag.delete |
| GET|HEAD | api/v1/admin/stores/{store}/users |  | App\Http\Controllers\Api\Admin\User\AdminUserController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.view |
| GET|HEAD | api/v1/admin/stores/{store}/users/{user} |  | App\Http\Controllers\Api\Admin\User\AdminUserController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.view |
| DELETE | api/v1/admin/stores/{store}/users/{user} |  | App\Http\Controllers\Api\Admin\User\AdminUserController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.delete |
| PATCH | api/v1/admin/stores/{store}/users/{user}/block |  | App\Http\Controllers\Api\Admin\User\AdminUserController@block | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.block |
| PATCH | api/v1/admin/stores/{store}/users/{user}/restore |  | App\Http\Controllers\Api\Admin\User\AdminUserController@restore | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.restore |
| PATCH | api/v1/admin/stores/{store}/users/{user}/unblock |  | App\Http\Controllers\Api\Admin\User\AdminUserController@unblock | api, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified, App\Http\Middleware\EnsureOnboardingIsCompleted, App\Http\Middleware\StoreContext, Spatie\Permission\Middleware\PermissionMiddleware:user.block |
| POST | api/v1/leads/contact |  | App\Http\Controllers\Api\Lead\LeadController@contact | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe, Illuminate\Routing\Middleware\ThrottleRequests:lead-submissions |
| POST | api/v1/leads/demo |  | App\Http\Controllers\Api\Lead\LeadController@demo | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe, Illuminate\Routing\Middleware\ThrottleRequests:lead-submissions |
| POST | api/v1/leads/enterprise |  | App\Http\Controllers\Api\Lead\LeadController@enterprise | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe, Illuminate\Routing\Middleware\ThrottleRequests:lead-submissions |
| GET|HEAD | api/v1/me | v1.me | App\Http\Controllers\Api\Auth\AuthController@bootstrap | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/platform/analytics |  | App\Http\Controllers\Api\Platform\PlatformAnalyticsController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/audit/logs |  | App\Http\Controllers\Api\Platform\PlatformAuditController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/audit/logs/{log} |  | App\Http\Controllers\Api\Platform\PlatformAuditController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/dashboard |  | App\Http\Controllers\Api\Platform\PlatformDashboardController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/features |  | App\Http\Controllers\Api\Platform\PlatformFeatureController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| PATCH | api/v1/platform/features/{feature} |  | App\Http\Controllers\Api\Platform\PlatformFeatureController@update | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/stores |  | App\Http\Controllers\Api\Platform\PlatformStoreController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/stores/{store} |  | App\Http\Controllers\Api\Platform\PlatformStoreController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| PATCH | api/v1/platform/stores/{store}/activate |  | App\Http\Controllers\Api\Platform\PlatformStoreController@activate | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| PATCH | api/v1/platform/stores/{store}/suspend |  | App\Http\Controllers\Api\Platform\PlatformStoreController@suspend | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/users |  | App\Http\Controllers\Api\Platform\PlatformUserController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/platform/users/{user} |  | App\Http\Controllers\Api\Platform\PlatformUserController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| PATCH | api/v1/platform/users/{user}/activate |  | App\Http\Controllers\Api\Platform\PlatformUserController@activate | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| PATCH | api/v1/platform/users/{user}/suspend |  | App\Http\Controllers\Api\Platform\PlatformUserController@suspend | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:platform,platform,enforce, App\Http\Middleware\EnforcePlatformAuthority:platform_admin |
| GET|HEAD | api/v1/public/cms/blog | public.blog.index | App\Http\Controllers\Api\Cms\Blog\PublicBlogController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/blog/{slug} | public.blog.show | App\Http\Controllers\Api\Cms\Blog\PublicBlogController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/docs/sidebar |  | App\Http\Controllers\Api\Cms\Documentation\PublicDocumentController@sidebar | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/docs/{slugPath} |  | App\Http\Controllers\Api\Cms\Documentation\PublicDocumentController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/docs/{slugPath}/navigation |  | App\Http\Controllers\Api\Cms\Documentation\PublicDocumentController@navigation | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/pages/{slug} |  | App\Http\Controllers\Api\Cms\Marketing\PublicMarketingController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/seo/robots.txt |  | App\Http\Controllers\Api\Cms\Seo\PublicCmsSeoController@robots | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/seo/sitemap/blog |  | App\Http\Controllers\Api\Cms\Seo\PublicCmsSeoController@blog | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/seo/sitemap/docs |  | App\Http\Controllers\Api\Cms\Seo\PublicCmsSeoController@docs | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/public/cms/seo/sitemap/marketing |  | App\Http\Controllers\Api\Cms\Seo\PublicCmsSeoController@marketing | api, App\Http\Middleware\ApplyIdentityRouteContext:public,customer,observe |
| GET|HEAD | api/v1/store-slug/check | stores.slug-check-global | App\Http\Controllers\Api\V1\StoreSlugController@__invoke | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified |
| GET|HEAD | api/v1/storefront/account/bootstrap | v1.storefront.account.bootstrap | App\Http\Controllers\Api\Storefront\Account\StorefrontAccountController@bootstrap | api, App\Http\Middleware\ApplyIdentityRouteContext:customer_account,customer,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| POST | api/v1/storefront/account/login | v1.storefront.account.login | App\Http\Controllers\Api\Storefront\Account\StorefrontAccountController@login | api, App\Http\Middleware\ApplyIdentityRouteContext:customer_account,customer,enforce, Illuminate\Routing\Middleware\ThrottleRequests:customer-login |
| POST | api/v1/storefront/account/logout | v1.storefront.account.logout | App\Http\Controllers\Api\Storefront\Account\StorefrontAccountController@logout | api, App\Http\Middleware\ApplyIdentityRouteContext:customer_account,customer,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/storefront/account/me | v1.storefront.account.me | App\Http\Controllers\Api\Storefront\Account\StorefrontAccountController@me | api, App\Http\Middleware\ApplyIdentityRouteContext:customer_account,customer,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| POST | api/v1/storefront/account/register | v1.storefront.account.register | App\Http\Controllers\Api\Storefront\Account\StorefrontAccountController@register | api, App\Http\Middleware\ApplyIdentityRouteContext:customer_account,customer,enforce |
| POST | api/v1/stores | stores.create | App\Http\Controllers\Api\Store\StoreController@create | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified |
| POST | api/v1/stores/validate-slug | stores.validate-slug | App\Http\Controllers\Api\Store\StoreController@validateSlug | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified |
| GET|HEAD | api/v1/stores/{store} | stores.show | App\Http\Controllers\Api\Store\StoreController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| PUT | api/v1/stores/{store} | stores.update | App\Http\Controllers\Api\Store\StoreController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/addresses | stores.addresses.index | App\Http\Controllers\Api\Address\AddressController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/addresses | stores.addresses.store | App\Http\Controllers\Api\Address\AddressController@store | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| PUT | api/v1/stores/{store}/addresses/{address} | stores.addresses.update | App\Http\Controllers\Api\Address\AddressController@update | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| DELETE | api/v1/stores/{store}/addresses/{address} | stores.addresses.destroy | App\Http\Controllers\Api\Address\AddressController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| PATCH | api/v1/stores/{store}/addresses/{address}/default | stores.addresses.setDefault | App\Http\Controllers\Api\Address\AddressController@setDefault | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/cart |  | App\Http\Controllers\Api\Cart\CartController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| DELETE | api/v1/stores/{store}/cart/clear |  | App\Http\Controllers\Api\Cart\CartController@clear | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/cart/items |  | App\Http\Controllers\Api\Cart\CartController@addItem | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| PATCH | api/v1/stores/{store}/cart/items/{itemId} |  | App\Http\Controllers\Api\Cart\CartController@updateItem | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| DELETE | api/v1/stores/{store}/cart/items/{itemId} |  | App\Http\Controllers\Api\Cart\CartController@removeItem | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/checkout | stores.checkout.initiate | App\Http\Controllers\Api\Payment\CheckoutController@initiate | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/checkout/confirm | stores.checkout.confirm | App\Http\Controllers\Api\Payment\CheckoutController@confirm | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/homepage/best-seller | stores.homepage.best-seller | App\Http\Controllers\Api\Homepage\HomePageController@bestSeller | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/homepage/hero | stores.homepage.hero | App\Http\Controllers\Api\Homepage\HomePageController@hero | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/orders |  | App\Http\Controllers\Api\Order\OrderController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/orders/filters |  | App\Http\Controllers\Api\Order\OrderController@filters | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/orders/{orderNumber} |  | App\Http\Controllers\Api\Order\OrderController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/orders/{orderNumber}/cancel |  | App\Http\Controllers\Api\Order\OrderController@cancel | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| POST | api/v1/stores/{store}/orders/{orderNumber}/reorder |  | App\Http\Controllers\Api\Order\OrderController@reorder | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/products | v1.stores.product.index | App\Http\Controllers\Api\Product\ProductController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/products/category/{slug} | v1.stores.product.category | App\Http\Controllers\Api\Product\ProductController@indexByCategory | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/products/{slug} | v1.stores.product.show | App\Http\Controllers\Api\Product\ProductController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/products/{slug}/related | v1.stores.product.related | App\Http\Controllers\Api\Product\ProductController@related | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/stores/{store}/provisioning-status | stores.provisioning-status | App\Http\Controllers\Api\V1\ProvisioningStatusController@__invoke | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_admin,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified |
| GET|HEAD | api/v1/stores/{store}/search | stores.search.index | App\Http\Controllers\Api\Search\SearchController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe, App\Http\Middleware\StoreContext |
| GET|HEAD | api/v1/support/dashboard |  | App\Http\Controllers\Api\Support\SupportDashboardController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/impersonation/active |  | App\Http\Controllers\Api\Support\SupportImpersonationController@active | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| POST | api/v1/support/impersonation/request |  | App\Http\Controllers\Api\Support\SupportImpersonationController@request | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| DELETE | api/v1/support/impersonation/terminate |  | App\Http\Controllers\Api\Support\SupportImpersonationController@terminate | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/stores/search |  | App\Http\Controllers\Api\Support\SupportStoreLookupController@search | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/stores/{store} |  | App\Http\Controllers\Api\Support\SupportStoreLookupController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/stores/{store}/activity |  | App\Http\Controllers\Api\Support\SupportStoreLookupController@activity | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/tickets |  | App\Http\Controllers\Api\Support\SupportTicketController@index | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/tickets/{ticket} |  | App\Http\Controllers\Api\Support\SupportTicketController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| PATCH | api/v1/support/tickets/{ticket}/assign |  | App\Http\Controllers\Api\Support\SupportTicketController@assign | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| POST | api/v1/support/tickets/{ticket}/notes |  | App\Http\Controllers\Api\Support\SupportTicketController@addNote | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| PATCH | api/v1/support/tickets/{ticket}/resolve |  | App\Http\Controllers\Api\Support\SupportTicketController@resolve | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/users/search |  | App\Http\Controllers\Api\Support\SupportUserLookupController@search | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/users/{user} |  | App\Http\Controllers\Api\Support\SupportUserLookupController@show | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| GET|HEAD | api/v1/support/users/{user}/activity |  | App\Http\Controllers\Api\Support\SupportUserLookupController@activity | api, Illuminate\Auth\Middleware\Authenticate:sanctum, App\Http\Middleware\ApplyIdentityRouteContext:support,platform,enforce, App\Http\Middleware\EnforceSupportAuthority |
| PATCH | api/v1/users/auth/active-store | v1.users.auth.active-store.update | App\Http\Controllers\Api\Auth\AuthController@updateActiveStore | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum, Illuminate\Auth\Middleware\EnsureEmailIsVerified |
| POST | api/v1/users/auth/email/resend | v1.users.auth.email.resend | App\Http\Controllers\Api\Auth\AuthController@resendVerificationEmail | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Routing\Middleware\ThrottleRequests:verification-resend |
| GET|HEAD | api/v1/users/auth/email/status | v1.users.auth.email.status | App\Http\Controllers\Api\V1\EmailVerificationController@status | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/users/auth/email/verify/{id}/{hash} | v1.users.auth.verification.verify | App\Http\Controllers\Api\Auth\AuthController@verifyEmail | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| GET|HEAD | api/v1/users/auth/google/callback | v1.users.auth. | App\Http\Controllers\Api\Auth\SocialAuthController@callback | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| GET|HEAD | api/v1/users/auth/google/redirect | v1.users.auth. | App\Http\Controllers\Api\Auth\SocialAuthController@redirect | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| POST | api/v1/users/auth/login | v1.users.auth.login | App\Http\Controllers\Api\Auth\AuthController@login | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Routing\Middleware\ThrottleRequests:login |
| POST | api/v1/users/auth/logout | v1.users.auth.logout | App\Http\Controllers\Api\Auth\AuthController@logout | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/users/auth/me | v1.users.auth.me | App\Http\Controllers\Api\Auth\AuthController@bootstrap | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| POST | api/v1/users/auth/password/forgot | v1.users.auth.password.forgot | App\Http\Controllers\Api\Auth\PasswordResetController@sendResetLink | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| POST | api/v1/users/auth/password/reset | v1.users.auth.password.reset | App\Http\Controllers\Api\Auth\PasswordResetController@reset | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| POST | api/v1/users/auth/password/validate-token | v1.users.auth.password.validate-token | App\Http\Controllers\Api\Auth\PasswordResetController@validateToken | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| POST | api/v1/users/auth/register | v1.users.auth.register | App\Http\Controllers\Api\Auth\AuthController@register | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| GET|HEAD | api/v1/users/categories/{category}/breadcrumb | v1.users.category.breadcrumb | App\Http\Controllers\Api\Category\CategoryController@breadcrumb | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| GET|HEAD | api/v1/users/checkout/status/{sessionId} |  | App\Http\Controllers\Api\Payment\CheckoutController@status | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce |
| POST | api/v1/users/orders/guest/lookup |  | App\Http\Controllers\Api\Order\OrderController@guestLookup | api, App\Http\Middleware\ApplyIdentityRouteContext:storefront_commerce,customer,observe |
| GET|HEAD | api/v1/users/profile |  | App\Http\Controllers\Api\Auth\ProfileController@show | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| DELETE | api/v1/users/profile |  | App\Http\Controllers\Api\Auth\ProfileController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| POST | api/v1/users/profile/avatar |  | App\Http\Controllers\Api\Auth\ProfileController@updateAvatar | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| PUT | api/v1/users/profile/info |  | App\Http\Controllers\Api\Auth\ProfileController@updateInfo | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| PUT | api/v1/users/profile/password |  | App\Http\Controllers\Api\Auth\ProfileController@updatePassword | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | api/v1/users/sessions | v1.users.sessions.index | App\Http\Controllers\Api\Auth\SessionController@index | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| DELETE | api/v1/users/sessions | v1.users.sessions.destroy-all | App\Http\Controllers\Api\Auth\SessionController@destroyAll | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| DELETE | api/v1/users/sessions/{id} | v1.users.sessions.destroy | App\Http\Controllers\Api\Auth\SessionController@destroy | api, App\Http\Middleware\ApplyIdentityRouteContext:merchant_users,merchant,enforce, Illuminate\Auth\Middleware\Authenticate:sanctum |
| GET|HEAD | docs/api | scramble.docs.ui | Closure | web, Dedoc\Scramble\Http\Middleware\RestrictedDocsAccess |
| GET|HEAD | docs/api.json | scramble.docs.document | Closure | web, Dedoc\Scramble\Http\Middleware\RestrictedDocsAccess |
| GET|POST|HEAD | graphql | graphql | Nuwave\Lighthouse\Http\GraphQLController | Nuwave\Lighthouse\Http\Middleware\AcceptJson, Nuwave\Lighthouse\Http\Middleware\AttemptAuthentication |
| GET|HEAD | graphql-playground | graphql-playground | MLL\GraphQLPlayground\GraphQLPlaygroundController@get |  |
| GET|HEAD | sanctum/csrf-cookie |  | Laravel\Sanctum\Http\Controllers\CsrfCookieController@show | web |
| GET|HEAD | scalar | scalar | Scalar\Controllers\ScalarController | web |
| GET|HEAD | storage/{path} | storage.local | Closure |  |
| GET|HEAD | up |  | Closure |  |
